= My First AsciiDoc

Per link:https://asciidoctor.org/docs/asciidoc-recommended-practices/[AsciiDoc Recommended Practices], each sentence should start on a seperate line.
A new line does not start a new paragraph.

[NOTE]
====
Placing each sentence on a new line is not required. This sentence is on the same line as the previous one. They are parts of the same paragraph.
====

== Line Breaks

A plus sign at the end of the line "+" +
Creates a hard line break.

== Paragraphs

At least one blank line between lines of text starts a new paragraph.
This is a new paragraph.

== Tables

There are many ways to make tables in AsciiDoc. The following are a few examples.

=== Include .csv

This table is generated from a seperate .csv, but it will not render from this .adoc when viewed on GitHub.
 
[%header, format=csv]
|====
include::basic table.csv[]
|====

=== Hardcode .csv 

I can also code a .csv directly into this .adoc:

[%header, format=csv]
|====
Head 1, Head 2, Head 3, Head 4
Row 1.1, Row 1.2, Row 1.3, Row 1.4
Row 2.1, Row 2.2, Row 2.3, Row 2.4
|====





