= My First AsciiDoc

Per link:https://asciidoctor.org/docs/asciidoc-recommended-practices/[AsciiDoc Recommended Practices], each sentence should start on a seperate line.
A new line does not start a new paragraph.

[NOTE]
====
Placing each sentence on a new line is not required. This sentence is on the same line as the previous one. They are parts of the same paragraph.

However, placing each sentence on it's own line cound be useful for includes that only reference certain lines of a file.
====

== Line Breaks

A plus sign at the end of the line "+" +
creates a hard line break.

== Paragraphs

At least one blank line between lines of text starts a new paragraph.

This is a new paragraph.

== Tables

There are many ways to make tables in AsciiDoc. The following are a few examples.

=== Include .csv

This table is generated from a seperate .csv, but it will not render from this .adoc when viewed on GitHub.
 
[%header, format=csv]
|====
include::basic table.csv[]
|====

=== Hardcode .csv 

The next table is coded as .csv directly into this .adoc. This will render when viewed on GitHub.

[%header, format=csv]
|====
Head 1, Head 2, Head 3, Head 4
Row 1.1, Row 1.2, Row 1.3, Row 1.4
Row 2.1, Row 2.2, Row 2.3, Row 2.4
|====

== Single-Sourced Footer

This copyright declaration is single sourced from a separate .adoc file.

=== Copyright Declaration

include::includes/copyright.adoc[]

NOTE: Includes don't render when viewed on GitHub. 



